Test.assertEquals(matchHouses(1), 6)
Test.assertEquals(matchHouses(0), 0)
Test.assertEquals(matchHouses(17), 86)
Test.assertEquals(matchHouses(36), 181)
Test.assertEquals(matchHouses(15), 76)
Test.assertEquals(matchHouses(99), 496)
Test.assertEquals(matchHouses(3), 16)
Test.assertEquals(matchHouses(87), 436)
